// <auto-generated />
using System;
using AutoMapperDemoConsole;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoMapperDemoConsole.Migrations
{
    [DbContext(typeof(AutoMapperDbContext))]
    [Migration("20220628110524_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("AutoMapperDemoConsole.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("PersonId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            EmailAddress = "liuxuande@han.com",
                            Password = "123456",
                            PersonId = 1,
                            Username = "liuxuande"
                        },
                        new
                        {
                            AccountId = 2,
                            Password = "123456",
                            PersonId = 1,
                            Username = "liuyuzhou"
                        },
                        new
                        {
                            AccountId = 3,
                            EmailAddress = "guanyunchang@han.com",
                            Password = "123456",
                            PersonId = 2,
                            Username = "guanyunchang"
                        },
                        new
                        {
                            AccountId = 4,
                            Password = "123456",
                            PersonId = 2,
                            Username = "meirangong"
                        });
                });

            modelBuilder.Entity("AutoMapperDemoConsole.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AddressId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "zhuoxian",
                            Country = "han",
                            DetailAddress = "liubeijia",
                            PersonId = 1,
                            Province = "zhuojun"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "unknown",
                            Country = "han",
                            DetailAddress = "zhangfeijia",
                            PersonId = 3,
                            Province = "zhuojun"
                        });
                });

            modelBuilder.Entity("AutoMapperDemoConsole.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Age = 63,
                            CreatedUtc = new DateTime(2022, 6, 28, 11, 5, 24, 31, DateTimeKind.Utc).AddTicks(3025),
                            FirstName = "Bei",
                            LastName = "Liu",
                            ModifiedUtc = new DateTime(2022, 7, 8, 11, 5, 24, 31, DateTimeKind.Utc).AddTicks(3026)
                        },
                        new
                        {
                            PersonId = 2,
                            Age = 60,
                            CreatedUtc = new DateTime(2022, 6, 28, 11, 5, 24, 31, DateTimeKind.Utc).AddTicks(3037),
                            FirstName = "Yu",
                            LastName = "Guan",
                            ModifiedUtc = new DateTime(2022, 7, 8, 11, 5, 24, 31, DateTimeKind.Utc).AddTicks(3037)
                        },
                        new
                        {
                            PersonId = 3,
                            Age = 58,
                            CreatedUtc = new DateTime(2022, 6, 28, 11, 5, 24, 31, DateTimeKind.Utc).AddTicks(3039),
                            FirstName = "Fei",
                            LastName = "Zhang"
                        });
                });

            modelBuilder.Entity("AutoMapperDemoConsole.Account", b =>
                {
                    b.HasOne("AutoMapperDemoConsole.Person", null)
                        .WithMany("Accounts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoMapperDemoConsole.Address", b =>
                {
                    b.HasOne("AutoMapperDemoConsole.Person", null)
                        .WithOne("Address")
                        .HasForeignKey("AutoMapperDemoConsole.Address", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoMapperDemoConsole.Person", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
